### PR TITLE
[fix] Dead link

### PR DESCRIPTION
**Pull request by frju365**
*micro-decision*
- [ ] Approval (LGTM)

### CODE REVIEW

**Comment by Psycojoker** [comment]
This one seems to be the good link https://impress.github.io/impress.js/#/bored

**Comment by frju365** [comment]
updated ! done ! (thanks for the link)

**Comment by alexAubin** [comment]
Bump ? Sounds like an easily mergeable PR ?

**Comment by Psycojoker** [comment]
Let's merge it then, I don't see the point of losing more time on it since it's only the README.

**Pull request merged**
